### ISSUE TITLE
Installation Issue

### ISSUE THREAD

**Issue by chaichana-t** [showlab/videollm-online#24]
Hi Contribution Team,

Thank you for your hard work on implementing VideoLLM. I encountered an issue during installation and subsequent execution.
1. Create new Conda environment using python version 3.10.14
2. Install dependencies using conda and pip
3. Install newest ffmpeg

Then I executed
```
python -m demo.app --resume_from_checkpoint chenjoya/videollm-online-8b-v1plus
```
I found below error
```
RuntimeError: video_reader video backend is not available. Please compile torchvision from source and try again
```

So I tried to directly install torchvision from [torchvision](https://github.com/pytorch/vision) but encountered another issue
```
Traceback (most recent call last):
  File "/harddrive/harddrive10tb/chaichana.t/miniconda3/envs/videollm/lib/python3.10/site-packages/transformers/utils/import_utils.py", line 1603, in _get_module
    return importlib.import_module("." + module_name, self.__name__)
  File "/harddrive/harddrive10tb/chaichana.t/miniconda3/envs/videollm/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/harddrive/harddrive10tb/chaichana.t/miniconda3/envs/videollm/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 32, in <module>
    from ...modeling_flash_attention_utils import _flash_attention_forward
  File "/harddrive/harddrive10tb/chaichana.t/miniconda3/envs/videollm/lib/python3.10/site-packages/transformers/modeling_flash_attention_utils.py", line 27, in <module>
    from flash_attn.bert_padding import index_first_axis, pad_input, unpad_input  # noqa
  File "/harddrive/harddrive10tb/chaichana.t/miniconda3/envs/videollm/lib/python3.10/site-packages/flash_attn/__init__.py", line 3, in <module>
    from flash_attn.flash_attn_interface import (
  File "/harddrive/harddrive10tb/chaichana.t/miniconda3/envs/videollm/lib/python3.10/site-packages/flash_attn/flash_attn_interface.py", line 10, in <module>
    import flash_attn_2_cuda as flash_attn_cuda
ImportError: /harddrive/harddrive10tb/chaichana.t/miniconda3/envs/videollm/lib/python3.10/site-packages/flash_attn_2_cuda.cpython-310-x86_64-linux-gnu.so: undefined symbol: _ZN2at4_ops5zeros4callEN3c108ArrayRefINS2_6SymIntEEENS2_8optionalINS2_10ScalarTypeEEENS6_INS2_6LayoutEEENS6_INS2_6DeviceEEENS6_IbEE

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/harddrive/harddrive10tb/chaichana.t/miniconda3/envs/videollm/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/harddrive/harddrive10tb/chaichana.t/miniconda3/envs/videollm/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/chaichana.t/adhoc/VideoLLM-online/demo/app.py", line 8, in <module>
    from .inference import LiveInfer
  File "/home/chaichana.t/adhoc/VideoLLM-online/demo/inference.py", line 6, in <module>
    from models import build_model_and_tokenizer, parse_args, fast_greedy_generate
  File "/home/chaichana.t/adhoc/VideoLLM-online/models/__init__.py", line 4, in <module>
    from .live_llama import build_live_llama as build_model_and_tokenizer
  File "/home/chaichana.t/adhoc/VideoLLM-online/models/live_llama/__init__.py", line 2, in <module>
    from .modeling_live_llama import LiveLlamaForCausalLM, build_live_llama
  File "/home/chaichana.t/adhoc/VideoLLM-online/models/live_llama/modeling_live_llama.py", line 3, in <module>
    from transformers import LlamaForCausalLM, Cache
  File "<frozen importlib._bootstrap>", line 1075, in _handle_fromlist
  File "/harddrive/harddrive10tb/chaichana.t/miniconda3/envs/videollm/lib/python3.10/site-packages/transformers/utils/import_utils.py", line 1594, in __getattr__
    value = getattr(module, name)
  File "/harddrive/harddrive10tb/chaichana.t/miniconda3/envs/videollm/lib/python3.10/site-packages/transformers/utils/import_utils.py", line 1593, in __getattr__
    module = self._get_module(self._class_to_module[name])
  File "/harddrive/harddrive10tb/chaichana.t/miniconda3/envs/videollm/lib/python3.10/site-packages/transformers/utils/import_utils.py", line 1605, in _get_module
    raise RuntimeError(
RuntimeError: Failed to import transformers.models.llama.modeling_llama because of the following error (look up to see its traceback):
/harddrive/harddrive10tb/chaichana.t/miniconda3/envs/videollm/lib/python3.10/site-packages/flash_attn_2_cuda.cpython-310-x86_64-linux-gnu.so: undefined symbol: _ZN2at4_ops5zeros4callEN3c108ArrayRefINS2_6SymIntEEENS2_8optionalINS2_10ScalarTypeEEENS6_INS2_6LayoutEEENS6_INS2_6DeviceEEENS6_IbEE
```

After that I tried to downgrade torch but found another one as well. I would appreciate it if you could specify the required versions of libraries or provide a `requirements.txt` file

**Comment by chenjoya** [comment]
Hi, many thanks for your interests! Same as #15 . could you try ```pip install av```? Then you can comment the line of torchvision.set_video_backend(video_reader).

**Comment by chaichana-t** [comment]
Hi @chenjoya,

Thanks for your help! I encountered another issue while running the demo in both Gradio and CLI with below traceback

```
Traceback (most recent call last):
  File "/harddrive/harddrive10tb/chaichana.t/miniconda3/envs/videollm/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/harddrive/harddrive10tb/chaichana.t/miniconda3/envs/videollm/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/chaichana.t/adhoc/VideoLLM-online/demo/cli.py", line 63, in <module>
    main(liveinfer)
  File "/home/chaichana.t/adhoc/VideoLLM-online/demo/cli.py", line 44, in main
    query, response = liveinfer()
  File "/home/chaichana.t/adhoc/VideoLLM-online/demo/inference.py", line 125, in __call__
    query, response = self._call_for_response(video_time, query)
  File "/home/chaichana.t/adhoc/VideoLLM-online/demo/inference.py", line 47, in _call_for_response
    output_ids, self.past_key_values = fast_greedy_generate(model=self.model, inputs_embeds=inputs_embeds, past_key_values=self.past_key_values, eos_token_id=self.eos_token_id, inplace_output_ids=self.inplace_output_ids)
  File "/home/chaichana.t/adhoc/VideoLLM-online/models/modeling_live.py", line 177, in fast_greedy_generate
    outputs = model(inputs_embeds=inputs_embeds, past_key_values=past_key_values, use_cache=True)
  File "/harddrive/harddrive10tb/chaichana.t/miniconda3/envs/videollm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/harddrive/harddrive10tb/chaichana.t/miniconda3/envs/videollm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/harddrive/harddrive10tb/chaichana.t/miniconda3/envs/videollm/lib/python3.10/site-packages/peft/peft_model.py", line 1577, in forward
    return self.base_model(
  File "/harddrive/harddrive10tb/chaichana.t/miniconda3/envs/videollm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/harddrive/harddrive10tb/chaichana.t/miniconda3/envs/videollm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/harddrive/harddrive10tb/chaichana.t/miniconda3/envs/videollm/lib/python3.10/site-packages/peft/tuners/tuners_utils.py", line 188, in forward
    return self.model.forward(*args, **kwargs)
  File "/home/chaichana.t/adhoc/VideoLLM-online/models/live_llama/modeling_live_llama.py", line 42, in forward
    outputs = super().forward(
  File "/harddrive/harddrive10tb/chaichana.t/miniconda3/envs/videollm/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 1189, in forward
    outputs = self.model(
  File "/harddrive/harddrive10tb/chaichana.t/miniconda3/envs/videollm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/harddrive/harddrive10tb/chaichana.t/miniconda3/envs/videollm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/harddrive/harddrive10tb/chaichana.t/miniconda3/envs/videollm/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 1001, in forward
    layer_outputs = decoder_layer(
  File "/harddrive/harddrive10tb/chaichana.t/miniconda3/envs/videollm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/harddrive/harddrive10tb/chaichana.t/miniconda3/envs/videollm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/harddrive/harddrive10tb/chaichana.t/miniconda3/envs/videollm/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 734, in forward
    hidden_states, self_attn_weights, present_key_value = self.self_attn(
  File "/harddrive/harddrive10tb/chaichana.t/miniconda3/envs/videollm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/harddrive/harddrive10tb/chaichana.t/miniconda3/envs/videollm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/harddrive/harddrive10tb/chaichana.t/miniconda3/envs/videollm/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 556, in forward
    attn_output = _flash_attention_forward(
  File "/harddrive/harddrive10tb/chaichana.t/miniconda3/envs/videollm/lib/python3.10/site-packages/transformers/modeling_flash_attention_utils.py", line 280, in _flash_attention_forward
    attn_output = flash_attn_varlen_func(
  File "/harddrive/harddrive10tb/chaichana.t/miniconda3/envs/videollm/lib/python3.10/site-packages/flash_attn/flash_attn_interface.py", line 1059, in flash_attn_varlen_func
    return FlashAttnVarlenFunc.apply(
  File "/harddrive/harddrive10tb/chaichana.t/miniconda3/envs/videollm/lib/python3.10/site-packages/torch/autograd/function.py", line 553, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "/harddrive/harddrive10tb/chaichana.t/miniconda3/envs/videollm/lib/python3.10/site-packages/flash_attn/flash_attn_interface.py", line 576, in forward
    out, q, k, v, out_padded, softmax_lse, S_dmask, rng_state = _flash_attn_varlen_forward(
  File "/harddrive/harddrive10tb/chaichana.t/miniconda3/envs/videollm/lib/python3.10/site-packages/flash_attn/flash_attn_interface.py", line 85, in _flash_attn_varlen_forward
    out, q, k, v, out_padded, softmax_lse, S_dmask, rng_state = flash_attn_cuda.varlen_fwd(
RuntimeError: batch size must be positive
```

**Comment by chenjoya** [comment]
I see. Could you share your flash-attn & pytorch version?

**Comment by chaichana-t** [comment]
flash-attn 2.5.6
pytorch 2.2.1

**Comment by hb-jw** [comment]
I encountered the same issue about 'batchsize must be positive', May I ask if you have resolved the issue?

**Comment by chenjoya** [comment]
Hi, do you have any updates?

**Comment by chaichana-t** [comment]
Hi @chenjoya,

After adding `--attn_implementation sdpa` in the command to launch the gradio demo, it worked! Thank you very much for your help.

**Comment by chaichana-t** [comment]
Hi @hb-jw,

Yes. I just added `--attn_implementation sdpa` in the command to launch the gradio demo.

`python -m demo.app --resume_from_checkpoint chenjoya/videollm-online-8b-v1plus --attn_implementation sdpa`

**Comment by chenjoya** [comment]
So happy to hear that. Feel free to ask questions!
