### ISSUE TITLE
RUN "Please describe what I am doing." error

### ISSUE THREAD

**Issue by Rane2021** [showlab/videollm-online#3]
Traceback (most recent call last):
  File "/root/miniconda3/envs/videollm/lib/python3.10/site-packages/gradio/queueing.py", line 532, in process_events
    response = await route_utils.call_process_api(
  File "/root/miniconda3/envs/videollm/lib/python3.10/site-packages/gradio/route_utils.py", line 276, in call_process_api
    output = await app.get_blocks().process_api(
  File "/root/miniconda3/envs/videollm/lib/python3.10/site-packages/gradio/blocks.py", line 1928, in process_api
    result = await self.call_function(
  File "/root/miniconda3/envs/videollm/lib/python3.10/site-packages/gradio/blocks.py", line 1526, in call_function
    prediction = await utils.async_iteration(iterator)
  File "/root/miniconda3/envs/videollm/lib/python3.10/site-packages/gradio/utils.py", line 656, in async_iteration
    return await iterator.__anext__()
  File "/root/miniconda3/envs/videollm/lib/python3.10/site-packages/gradio/utils.py", line 649, in __anext__
    return await anyio.to_thread.run_sync(
  File "/root/miniconda3/envs/videollm/lib/python3.10/site-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "/root/miniconda3/envs/videollm/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 2177, in run_sync_in_worker_thread
    return await future
  File "/root/miniconda3/envs/videollm/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 859, in run
    result = context.run(func, *args)
  File "/root/miniconda3/envs/videollm/lib/python3.10/site-packages/gradio/utils.py", line 632, in run_sync_iterator_async
    return next(iterator)
  File "/root/miniconda3/envs/videollm/lib/python3.10/site-packages/gradio/utils.py", line 815, in gen_wrapper
    response = next(iterator)
  File "/data3/2024-projects/26_video_gen/videollm-online/demo/app.py", line 89, in gr_liveinfer_queue_refresher_change
    history[-1][1] += f'\n{response}'
IndexError: list index out of range

**Comment by chenjoya** [comment]
Could you describe your operation

**Comment by Rane2021** [comment]
thanks!, Exactly the opposite order

**Comment by chenjoya** [comment]
Thank you. Or you can make the video playing, then input query. If you want to have faster inference, cli is recommended
