### ISSUE TITLE
no adapter_model.bin weight on hf

### ISSUE THREAD

**Issue by nanamma** [showlab/videollm-online#36]
```bash
Cannot access gated repo for url https://huggingface.co/chenjoya/videollm-online-8b-v1plus/resolve/main/adapter_model.bin.
Access to model chenjoya/videollm-online-8b-v1plus is restricted. You must have access to it and be authenticated to access it. Please log in.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "****/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "****/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "***/videollm-online/demo/cli.py", line 53, in <module>
    liveinfer = LiveInfer()
  File "***/videollm-online/demo/inference.py", line 15, in __init__
    self.model, self.tokenizer = build_model_and_tokenizer(is_training=False, set_vision_inside=True, **asdict(args))
  File "***/videollm-online/models/live_llama/modeling_live_llama.py", line 73, in build_live_llama
    return build_live(config_class=LiveLlamaConfig, model_class=LiveLlamaForCausalLM, **kwargs)
  File "***/videollm-online/models/modeling_live.py", line 216, in build_live
    model = PeftModel.from_pretrained(model, resume_from_checkpoint, is_trainable=False)
  File "****/lib/python3.10/site-packages/peft/peft_model.py", line 181, in from_pretrained
    model.load_adapter(model_id, adapter_name, **kwargs)
  File "****/lib/python3.10/site-packages/peft/peft_model.py", line 367, in load_adapter
    raise ValueError(
ValueError: Can't find weights for chenjoya/videollm-online-8b-v1plus in chenjoya/videollm-online-8b-v1plus or in the Hugging Face Hub. Please check that the file adapter_model.bin is present at chenjoya/videollm-online-8b-v1plus.
```

**Comment by chenjoya** [comment]
Seems to be a peft or transformers version problem. Could you show the info of peft & transformers?

**Comment by nanamma** [comment]
I upgrade the version of `peft`. Then the problem is solved.
Thank you!🤗
